#!/bin/bash
##############################################################################
# Copyright (c) 2017 The Linux Foundation.  All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html
##############################################################################

i=0
while [[ $(tr -d "\r\n" < test.log | wc -c) -gt 0 ]];
do
    echo loop $i
    ((i++))
    for item in $(cat test.log);
    do
        project=$(echo $item | cut -f1 -d:)
        dependencies=$(echo $item | cut -f2 -d:)

        if [[ $dependencies == "" ]]; then
            echo Building $project
            sed -i "/$project:/d" test.log
            sed -i "s/$project//" test.log
        fi
    done

    # Clear up extra commas
    sed -i 's/,$//; s/,,/,/' test.log
    sleep 3
done
